/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
// eslint-disable-next-line prettier/prettier
import tokenJson from "../components/assets/MyToken.json";
import ballotJson from "../components/assets/TokenizedBallot.json";
import { Abi } from "viem";
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  11155111: {
    TokenizedBallot: {
      address: "0x6d08d3a93bce4cec4b27eb93307589bfecc42525",
      abi: ballotJson.abi as Abi,
    },
    MyToken: {
      address: "0xa58d7a0636135073f38cc45e166f6f518622838c",
      abi: tokenJson.abi as Abi,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
